### ISSUE TITLE
AI interprets fingernails as toes

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#62] opened 2021-03-04 03:35 UTC
Steps to reproduce:
- run the app as instructed in the readme
- create a user
- sign in via the login page
- click the upload button and upload an image of a hand

Expected: AI should recognize a hand is not a foot
Actual: fingernails recognized as toes

![image](https://user-images.githubusercontent.com/47096316/109907599-9e5cdf00-7c70-11eb-8594-e3ad7739cd40.png)

**Comment by Skeli789** [comment] 2021-03-07 21:46
Duplicate of #13

**Closed by Skeli789** 2021-03-07 21:46 UTC
Labels: duplicate
