### ISSUE TITLE
Cannot progress if uploaded picture is not of foot

### ISSUE THREAD

**Issue by nikhail-singh** [behdadkha/ToeFX#27] opened 2021-02-26 04:56 UTC
### Description
If you upload an image that's not a foot, it will let you upload and give you the "Please Choose the toe nails you would like to save" dialogue but there is nowhere to click and no way on the page to get rid of the image or choose a different one
### Browser and OS
Google Chrome on Windows 10
### Steps to recreate
1. go to the upload toe page
2. choose either left/right foot
3.  click upload
4. choose a photo that is not of a foot

**Comment by Skeli789** [comment] 2021-03-07 21:34
Duplicate of #14

**Closed by Skeli789** 2021-03-07 21:34 UTC
Labels: duplicate
