### ISSUE TITLE
Upload Page - Toenail preview save, multiple toenail preview selection

### ISSUE THREAD

**Issue by connorhewick** [behdadkha/ToeFX#24] opened 2021-02-26 01:28 UTC
When selected multiple toenail images to keep and save and select the correct toe will change the selection for all toenail images to keep.
To reproduce: upload an image. select multiple toenail as 'keep'. select a given toe and on a given preview and see the selection change on all toenails.
![Screen Shot 2021-02-25 at 8 24 01 PM](https://user-images.githubusercontent.com/37413894/109241761-e0d17800-77a7-11eb-870e-25fd78ee2562.png)

**Comment by Skeli789** [comment] 2021-03-07 21:32
Duplicate of #2

**Closed by Skeli789** 2021-03-07 21:32 UTC
Labels: duplicate
