### ISSUE TITLE
Placeholder string in password section is an improperly formatted password

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#66] opened 2021-03-04 22:36 UTC
The placeholder string for the password should be a valid password.

Environment: Windows, Google Chrome
Steps to Reproduce

- Navigate to the create account page
- Notice the placeholder text in password field

**Comment by Skeli789** [comment] 2021-03-07 21:47
Duplicate of #50

**Closed by Skeli789** 2021-03-07 21:47 UTC
Labels: duplicate
