### ISSUE TITLE
When multiple toes are found by the algorithm changing you cannot select different toes

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#67] opened 2021-03-04 23:02 UTC
![image](https://user-images.githubusercontent.com/16761051/110042409-bcc7e680-7d13-11eb-8e60-22a73bf3690b.png)
Changing one option changes all of them to the same toe.

Environment: Windows, Google Chrome
Steps to Reproduce

- Upload an image with multiple toes exposed
- Click the which toe dialogue
- All boxes will change in tandem

**Comment by Skeli789** [comment] 2021-03-07 21:48
Duplicate of #2

**Closed by Skeli789** 2021-03-07 21:48 UTC
Labels: duplicate
