### ISSUE TITLE
Clicking ToeFX on landing page leads to different home page

### ISSUE THREAD

**Issue by Gabriel-Gebril** [behdadkha/ToeFX#69] opened 2021-03-04 23:15 UTC
Clicking on ToeFX in header should lead to the same home page, right now "Home" and ToeFX lead to 2 different URLs.

**Comment by Gabriel-Gebril** [comment] 2021-03-05 00:29
Environment: Windows, Google Chrome
Steps to Reproduce

- Visit localhost:3000
-  Click "ToeFX" in upper left hand corner

**Comment by Skeli789** [comment] 2021-03-07 21:49
Duplicate of #44

**Closed by Skeli789** 2021-03-07 21:49 UTC
Labels: duplicate
