### ISSUE TITLE
[Dashboard] The labels disappear under the graph after clicking on them for several times

### ISSUE THREAD

**Issue by FangY2019** [behdadkha/ToeFX#35] opened 2021-02-26 15:48 UTC
## Environment

Device: ASUS Laptop
OS: Windows 10
Browser: Google Chrome

## Steps to Reproduce

1. Upload Image
2. Choose Left foot
3. Keep the first toenail as big toe
4. Go back to Dashboard
5. Click on the Big Toe under the graph
6. Click on the Index Toe under the graph

	
## Expected Result

The labels should turn to be grey

## Actual Result
The labels disappear

## Screenshot
Ater click the label of Big Toe:
![toe11](https://user-images.githubusercontent.com/54195303/109322514-64c74680-7820-11eb-8088-648fe9c0cd67.PNG)
Ater click the label of Index Toe:
![toe13](https://user-images.githubusercontent.com/54195303/109322302-23cf3200-7820-11eb-8187-68be2fe4ff93.PNG)

## Severity
LOW

**Comment by Skeli789** [comment] 2021-03-07 21:37
Duplicate of #15

**Closed by Skeli789** 2021-03-07 21:37 UTC
