### ISSUE TITLE
Upload Image: Changing selected foot during processing resets the process

### ISSUE THREAD

**Issue by anthonylou** [behdadkha/ToeFX#92] opened 2021-03-08 11:53 UTC
Steps to recreate:
1. Navigate to the "Upload Image" screen.
2. Select the L foot icon and upload an image.
3. While the image is processing, select the R foot icon. 

The process is reset, and may elongate processing times for the user (they may have mistakenly selected the wrong foot icon).

**Comment by Skeli789** [comment] 2021-03-11 01:26
Duplicate of #12

**Closed by Skeli789** 2021-03-11 01:26 UTC
Labels: duplicate
