### ISSUE TITLE
Uploading an image that is not a foot reaches state that has no available actions

### ISSUE THREAD

**Issue by robertjvardy** [behdadkha/ToeFX#61] opened 2021-03-04 03:30 UTC
Steps to reproduce:
- run the app as instructed
- create a user via the sign in page
- login using the login page
- select upload from the side bar
- upload an image that is clearly not a foot

Expected: feedbakc stating the image is not a foot
Actual: user is prompted to select toes but no actions are available (see image)

![image](https://user-images.githubusercontent.com/47096316/109907202-da437480-7c6f-11eb-8167-c9dbd23cfdc8.png)

**Comment by Skeli789** [comment] 2021-03-07 21:44
Duplicate of #14

**Closed by Skeli789** 2021-03-07 21:44 UTC
Labels: duplicate
