### ISSUE TITLE
Signup Age field: If field is a floating point number, request hangs

### ISSUE THREAD

**Issue by DavidHospital** [behdadkha/ToeFX#75] opened 2021-03-05 23:44 UTC
When creating a new account, if age is set to a floating point number (which input fields accepts), pressing "Create Account" hangs the webpage (presumably forever?) and does not display an error for an invalid age. When looking into the network tab in chrome developer tools, it seems that the first request sent to "localhost:3001/signup" is stuck "pending".

I have attempted this several times, and the page request hangs each time. When inputting a valid age (non-negative integer), the webpage behaves as expected. 

![signup_forever_request](https://user-images.githubusercontent.com/19175976/110186214-84dba480-7de2-11eb-8246-3dfa125e853a.PNG)

**Comment by DavidHospital** [comment] 2021-03-05 23:53
After closing the server, I noticed this error logged:
`  errors: {
    age: ValidatorError: {value} is not an integer value
        at validate (/toefx-server/node_modules/mongoose/lib/schematype.js:1222:13)
        at /toefx-server/node_modules/mongoose/lib/schematype.js:1205:7
        at Array.forEach (<anonymous>)
        at SchemaNumber.SchemaType.doValidate (/toefx-server/node_modules/mongoose/lib/schematype.js:1150:14)
        at /toefx-server/node_modules/mongoose/lib/document.js:2439:18
        at processTicksAndRejections (internal/process/task_queues.js:79:11) {
      properties: [Object],
      kind: 'user defined',
      path: 'age',
      value: 76.1,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'user validation failed'`

**Comment by Skeli789** [comment] 2021-03-07 21:51
Duplicate of #11

**Closed by Skeli789** 2021-03-07 21:51 UTC
Labels: duplicate
